# .github/workflows/code-quality.yml
name: Code Quality

on:
  push:
    branches: [ main, master, dev ]
  pull_request:
    branches: [ main, master, dev ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 black isort mypy
        pip install -r backend/requirements.txt

    - name: Basic syntax check
      run: |
        # Проверяем только критичные синтаксические ошибки
        flake8 backend --count --select=E9,F63,F7,F82 --show-source --statistics

    - name: Check imports (optional)
      run: |
        # Проверяем импорты, но не останавливаем на ошибках
        isort --check-only --profile black backend || echo "Import order issues found, but continuing..."
        
    - name: Type checking (optional)
      run: |
        # Запускаем mypy, но не останавливаем на ошибках  
        mypy backend --ignore-missing-imports || echo "Type checking issues found, but continuing..."
